DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS rechnung;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE rechnung (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  amount FLOAT,
  urheber_id INTEGER NOT NULL,
  schuldiger_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  FOREIGN KEY (urheber_id) REFERENCES user(id)
);

CREATE TABLE history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  amount FLOAT,
  urheber_id INTEGER NOT NULL,
  schuldiger_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  FOREIGN KEY (urheber_id) REFERENCES user(id)
);

